<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerS7tgrcz\installerProdDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerS7tgrcz/installerProdDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerS7tgrcz.legacy');

    return;
}

if (!\class_exists(installerProdDebugProjectContainer::class, false)) {
    \class_alias(\ContainerS7tgrcz\installerProdDebugProjectContainer::class, installerProdDebugProjectContainer::class, false);
}

return new \ContainerS7tgrcz\installerProdDebugProjectContainer(array(
    'container.build_hash' => 'S7tgrcz',
    'container.build_id' => '2ea9760a',
    'container.build_time' => 1545659180,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerS7tgrcz');
