parameters:
    CustomImageUploadClass : 'AppBundle\Model\DefaultProduct'
    CdnPathClass : '\Pimcore\Model\DataObject\Fieldcollection\Data\CdnPath'
    MainImageUploadField : 'main'
    ImageGalleryUploadField : 'gallery'
    MainImageFields:
        main1:
            thumbnail: main1
        main2:
            thumbnail: main2
        main3:
            thumbnail: main3
    ImageGalleryFields:
        gallery1:
            thumbnail: gallery1
        gallery2:
            thumbnail: gallery2
    CdnPathFields:
        small:
            thumbnail: main1
        medium:
            thumbnail: main2
        large:
            thumbnail: main3