parameters:
    MainImageFields:
        main1:
            thumbnail: main1
        main2:
            thumbnail: main2
        main3:
            thumbnail: main3
    ImageGallaryFields:
        gallery1:
            thumbnail: gallery1
        gallery2:
            thumbnail: gallery2